// Code generated by MockGen. DO NOT EDIT.
// Source: db/sqlc/querier.go

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/qwetu_petro/backend/db/sqlc"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// ApprovePaymentRequest mocks base method.
func (m *MockQuerier) ApprovePaymentRequest(ctx context.Context, arg db.ApprovePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePaymentRequest", ctx, arg)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePaymentRequest indicates an expected call of ApprovePaymentRequest.
func (mr *MockQuerierMockRecorder) ApprovePaymentRequest(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePaymentRequest", reflect.TypeOf((*MockQuerier)(nil).ApprovePaymentRequest), ctx, arg)
}

// ApprovePettyCash mocks base method.
func (m *MockQuerier) ApprovePettyCash(ctx context.Context, arg db.ApprovePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePettyCash", ctx, arg)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePettyCash indicates an expected call of ApprovePettyCash.
func (mr *MockQuerierMockRecorder) ApprovePettyCash(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePettyCash", reflect.TypeOf((*MockQuerier)(nil).ApprovePettyCash), ctx, arg)
}

// ApprovePurchaseOrder mocks base method.
func (m *MockQuerier) ApprovePurchaseOrder(ctx context.Context, arg db.ApprovePurchaseOrderParams) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApprovePurchaseOrder", ctx, arg)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApprovePurchaseOrder indicates an expected call of ApprovePurchaseOrder.
func (mr *MockQuerierMockRecorder) ApprovePurchaseOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApprovePurchaseOrder", reflect.TypeOf((*MockQuerier)(nil).ApprovePurchaseOrder), ctx, arg)
}

// CreateBankDetails mocks base method.
func (m *MockQuerier) CreateBankDetails(ctx context.Context, arg db.CreateBankDetailsParams) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankDetails", ctx, arg)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankDetails indicates an expected call of CreateBankDetails.
func (mr *MockQuerierMockRecorder) CreateBankDetails(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankDetails", reflect.TypeOf((*MockQuerier)(nil).CreateBankDetails), ctx, arg)
}

// CreateCar mocks base method.
func (m *MockQuerier) CreateCar(ctx context.Context, arg db.CreateCarParams) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", ctx, arg)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockQuerierMockRecorder) CreateCar(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockQuerier)(nil).CreateCar), ctx, arg)
}

// CreateCompany mocks base method.
func (m *MockQuerier) CreateCompany(ctx context.Context, arg db.CreateCompanyParams) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", ctx, arg)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockQuerierMockRecorder) CreateCompany(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockQuerier)(nil).CreateCompany), ctx, arg)
}

// CreateFuelConsumption mocks base method.
func (m *MockQuerier) CreateFuelConsumption(ctx context.Context, arg db.CreateFuelConsumptionParams) (db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFuelConsumption", ctx, arg)
	ret0, _ := ret[0].(db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFuelConsumption indicates an expected call of CreateFuelConsumption.
func (mr *MockQuerierMockRecorder) CreateFuelConsumption(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFuelConsumption", reflect.TypeOf((*MockQuerier)(nil).CreateFuelConsumption), ctx, arg)
}

// CreateInvoice mocks base method.
func (m *MockQuerier) CreateInvoice(ctx context.Context, arg db.CreateInvoiceParams) (db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, arg)
	ret0, _ := ret[0].(db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockQuerierMockRecorder) CreateInvoice(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockQuerier)(nil).CreateInvoice), ctx, arg)
}

// CreateInvoiceItem mocks base method.
func (m *MockQuerier) CreateInvoiceItem(ctx context.Context, arg db.CreateInvoiceItemParams) (db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoiceItem", ctx, arg)
	ret0, _ := ret[0].(db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoiceItem indicates an expected call of CreateInvoiceItem.
func (mr *MockQuerierMockRecorder) CreateInvoiceItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoiceItem", reflect.TypeOf((*MockQuerier)(nil).CreateInvoiceItem), ctx, arg)
}

// CreatePaymentRequest mocks base method.
func (m *MockQuerier) CreatePaymentRequest(ctx context.Context, arg db.CreatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentRequest", ctx, arg)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentRequest indicates an expected call of CreatePaymentRequest.
func (mr *MockQuerierMockRecorder) CreatePaymentRequest(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentRequest", reflect.TypeOf((*MockQuerier)(nil).CreatePaymentRequest), ctx, arg)
}

// CreatePettyCash mocks base method.
func (m *MockQuerier) CreatePettyCash(ctx context.Context, arg db.CreatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePettyCash", ctx, arg)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePettyCash indicates an expected call of CreatePettyCash.
func (mr *MockQuerierMockRecorder) CreatePettyCash(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePettyCash", reflect.TypeOf((*MockQuerier)(nil).CreatePettyCash), ctx, arg)
}

// CreatePurchaseOrder mocks base method.
func (m *MockQuerier) CreatePurchaseOrder(ctx context.Context, arg db.CreatePurchaseOrderParams) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseOrder", ctx, arg)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchaseOrder indicates an expected call of CreatePurchaseOrder.
func (mr *MockQuerierMockRecorder) CreatePurchaseOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseOrder", reflect.TypeOf((*MockQuerier)(nil).CreatePurchaseOrder), ctx, arg)
}

// CreatePurchaseOrderItem mocks base method.
func (m *MockQuerier) CreatePurchaseOrderItem(ctx context.Context, arg db.CreatePurchaseOrderItemParams) (db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchaseOrderItem", ctx, arg)
	ret0, _ := ret[0].(db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchaseOrderItem indicates an expected call of CreatePurchaseOrderItem.
func (mr *MockQuerierMockRecorder) CreatePurchaseOrderItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchaseOrderItem", reflect.TypeOf((*MockQuerier)(nil).CreatePurchaseOrderItem), ctx, arg)
}

// CreateQuotation mocks base method.
func (m *MockQuerier) CreateQuotation(ctx context.Context, arg db.CreateQuotationParams) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuotation", ctx, arg)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuotation indicates an expected call of CreateQuotation.
func (mr *MockQuerierMockRecorder) CreateQuotation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuotation", reflect.TypeOf((*MockQuerier)(nil).CreateQuotation), ctx, arg)
}

// CreateQuotationItem mocks base method.
func (m *MockQuerier) CreateQuotationItem(ctx context.Context, arg db.CreateQuotationItemParams) (db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuotationItem", ctx, arg)
	ret0, _ := ret[0].(db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuotationItem indicates an expected call of CreateQuotationItem.
func (mr *MockQuerierMockRecorder) CreateQuotationItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuotationItem", reflect.TypeOf((*MockQuerier)(nil).CreateQuotationItem), ctx, arg)
}

// CreateRole mocks base method.
func (m *MockQuerier) CreateRole(ctx context.Context, arg db.CreateRoleParams) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, arg)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockQuerierMockRecorder) CreateRole(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockQuerier)(nil).CreateRole), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockQuerier) CreateSession(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockQuerierMockRecorder) CreateSession(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockQuerier)(nil).CreateSession), ctx, arg)
}

// CreateSignatory mocks base method.
func (m *MockQuerier) CreateSignatory(ctx context.Context, arg db.CreateSignatoryParams) (db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSignatory", ctx, arg)
	ret0, _ := ret[0].(db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSignatory indicates an expected call of CreateSignatory.
func (mr *MockQuerierMockRecorder) CreateSignatory(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignatory", reflect.TypeOf((*MockQuerier)(nil).CreateSignatory), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// CreateUserRoles mocks base method.
func (m *MockQuerier) CreateUserRoles(ctx context.Context, arg db.CreateUserRolesParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRoles", ctx, arg)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserRoles indicates an expected call of CreateUserRoles.
func (mr *MockQuerierMockRecorder) CreateUserRoles(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRoles", reflect.TypeOf((*MockQuerier)(nil).CreateUserRoles), ctx, arg)
}

// DeleteCompanyByName mocks base method.
func (m *MockQuerier) DeleteCompanyByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompanyByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompanyByName indicates an expected call of DeleteCompanyByName.
func (mr *MockQuerierMockRecorder) DeleteCompanyByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompanyByName", reflect.TypeOf((*MockQuerier)(nil).DeleteCompanyByName), ctx, name)
}

// DeletePaymentRequest mocks base method.
func (m *MockQuerier) DeletePaymentRequest(ctx context.Context, requestID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePaymentRequest", ctx, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePaymentRequest indicates an expected call of DeletePaymentRequest.
func (mr *MockQuerierMockRecorder) DeletePaymentRequest(ctx, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePaymentRequest", reflect.TypeOf((*MockQuerier)(nil).DeletePaymentRequest), ctx, requestID)
}

// DeletePettyCash mocks base method.
func (m *MockQuerier) DeletePettyCash(ctx context.Context, transactionID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePettyCash", ctx, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePettyCash indicates an expected call of DeletePettyCash.
func (mr *MockQuerierMockRecorder) DeletePettyCash(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePettyCash", reflect.TypeOf((*MockQuerier)(nil).DeletePettyCash), ctx, transactionID)
}

// DeleteRole mocks base method.
func (m *MockQuerier) DeleteRole(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockQuerierMockRecorder) DeleteRole(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockQuerier)(nil).DeleteRole), ctx, id)
}

// DeleteSignatoryByName mocks base method.
func (m *MockQuerier) DeleteSignatoryByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSignatoryByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSignatoryByName indicates an expected call of DeleteSignatoryByName.
func (mr *MockQuerierMockRecorder) DeleteSignatoryByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSignatoryByName", reflect.TypeOf((*MockQuerier)(nil).DeleteSignatoryByName), ctx, name)
}

// DeleteUser mocks base method.
func (m *MockQuerier) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockQuerierMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockQuerier)(nil).DeleteUser), ctx, id)
}

// DeleteUserRoles mocks base method.
func (m *MockQuerier) DeleteUserRoles(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoles", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoles indicates an expected call of DeleteUserRoles.
func (mr *MockQuerierMockRecorder) DeleteUserRoles(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoles", reflect.TypeOf((*MockQuerier)(nil).DeleteUserRoles), ctx, userID)
}

// DeleteUserRolesByRole mocks base method.
func (m *MockQuerier) DeleteUserRolesByRole(ctx context.Context, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRolesByRole", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRolesByRole indicates an expected call of DeleteUserRolesByRole.
func (mr *MockQuerierMockRecorder) DeleteUserRolesByRole(ctx, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRolesByRole", reflect.TypeOf((*MockQuerier)(nil).DeleteUserRolesByRole), ctx, roleID)
}

// GetBankDetailsByAccountNumber mocks base method.
func (m *MockQuerier) GetBankDetailsByAccountNumber(ctx context.Context, accountNumber string) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankDetailsByAccountNumber", ctx, accountNumber)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankDetailsByAccountNumber indicates an expected call of GetBankDetailsByAccountNumber.
func (mr *MockQuerierMockRecorder) GetBankDetailsByAccountNumber(ctx, accountNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankDetailsByAccountNumber", reflect.TypeOf((*MockQuerier)(nil).GetBankDetailsByAccountNumber), ctx, accountNumber)
}

// GetBankInfoByID mocks base method.
func (m *MockQuerier) GetBankInfoByID(ctx context.Context, id int32) (db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankInfoByID", ctx, id)
	ret0, _ := ret[0].(db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankInfoByID indicates an expected call of GetBankInfoByID.
func (mr *MockQuerierMockRecorder) GetBankInfoByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankInfoByID", reflect.TypeOf((*MockQuerier)(nil).GetBankInfoByID), ctx, id)
}

// GetCarById mocks base method.
func (m *MockQuerier) GetCarById(ctx context.Context, id int32) (db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarById", ctx, id)
	ret0, _ := ret[0].(db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarById indicates an expected call of GetCarById.
func (mr *MockQuerierMockRecorder) GetCarById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarById", reflect.TypeOf((*MockQuerier)(nil).GetCarById), ctx, id)
}

// GetCars mocks base method.
func (m *MockQuerier) GetCars(ctx context.Context, arg db.GetCarsParams) ([]db.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCars", ctx, arg)
	ret0, _ := ret[0].([]db.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCars indicates an expected call of GetCars.
func (mr *MockQuerierMockRecorder) GetCars(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCars", reflect.TypeOf((*MockQuerier)(nil).GetCars), ctx, arg)
}

// GetCompanyByID mocks base method.
func (m *MockQuerier) GetCompanyByID(ctx context.Context, id int64) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByID", ctx, id)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyByID indicates an expected call of GetCompanyByID.
func (mr *MockQuerierMockRecorder) GetCompanyByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByID", reflect.TypeOf((*MockQuerier)(nil).GetCompanyByID), ctx, id)
}

// GetConsumptionByCar mocks base method.
func (m *MockQuerier) GetConsumptionByCar(ctx context.Context, carID int32) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptionByCar", ctx, carID)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptionByCar indicates an expected call of GetConsumptionByCar.
func (mr *MockQuerierMockRecorder) GetConsumptionByCar(ctx, carID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptionByCar", reflect.TypeOf((*MockQuerier)(nil).GetConsumptionByCar), ctx, carID)
}

// GetConsumptionByCarAndDateRange mocks base method.
func (m *MockQuerier) GetConsumptionByCarAndDateRange(ctx context.Context, arg db.GetConsumptionByCarAndDateRangeParams) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptionByCarAndDateRange", ctx, arg)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptionByCarAndDateRange indicates an expected call of GetConsumptionByCarAndDateRange.
func (mr *MockQuerierMockRecorder) GetConsumptionByCarAndDateRange(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptionByCarAndDateRange", reflect.TypeOf((*MockQuerier)(nil).GetConsumptionByCarAndDateRange), ctx, arg)
}

// GetConsumptions mocks base method.
func (m *MockQuerier) GetConsumptions(ctx context.Context, arg db.GetConsumptionsParams) ([]db.CarFuelConsumption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsumptions", ctx, arg)
	ret0, _ := ret[0].([]db.CarFuelConsumption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsumptions indicates an expected call of GetConsumptions.
func (mr *MockQuerierMockRecorder) GetConsumptions(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsumptions", reflect.TypeOf((*MockQuerier)(nil).GetConsumptions), ctx, arg)
}

// GetInvoiceById mocks base method.
func (m *MockQuerier) GetInvoiceById(ctx context.Context, id int32) (db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceById", ctx, id)
	ret0, _ := ret[0].(db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceById indicates an expected call of GetInvoiceById.
func (mr *MockQuerierMockRecorder) GetInvoiceById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceById", reflect.TypeOf((*MockQuerier)(nil).GetInvoiceById), ctx, id)
}

// GetInvoiceItemsByInvoiceID mocks base method.
func (m *MockQuerier) GetInvoiceItemsByInvoiceID(ctx context.Context, invoiceID int32) ([]db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceItemsByInvoiceID", ctx, invoiceID)
	ret0, _ := ret[0].([]db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceItemsByInvoiceID indicates an expected call of GetInvoiceItemsByInvoiceID.
func (mr *MockQuerierMockRecorder) GetInvoiceItemsByInvoiceID(ctx, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceItemsByInvoiceID", reflect.TypeOf((*MockQuerier)(nil).GetInvoiceItemsByInvoiceID), ctx, invoiceID)
}

// GetInvoicesByPurchaseOrderNumber mocks base method.
func (m *MockQuerier) GetInvoicesByPurchaseOrderNumber(ctx context.Context, purchaseOrderNumber string) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicesByPurchaseOrderNumber", ctx, purchaseOrderNumber)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoicesByPurchaseOrderNumber indicates an expected call of GetInvoicesByPurchaseOrderNumber.
func (mr *MockQuerierMockRecorder) GetInvoicesByPurchaseOrderNumber(ctx, purchaseOrderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicesByPurchaseOrderNumber", reflect.TypeOf((*MockQuerier)(nil).GetInvoicesByPurchaseOrderNumber), ctx, purchaseOrderNumber)
}

// GetPaymentRequest mocks base method.
func (m *MockQuerier) GetPaymentRequest(ctx context.Context, requestID int32) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentRequest", ctx, requestID)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentRequest indicates an expected call of GetPaymentRequest.
func (mr *MockQuerierMockRecorder) GetPaymentRequest(ctx, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentRequest", reflect.TypeOf((*MockQuerier)(nil).GetPaymentRequest), ctx, requestID)
}

// GetPettyCash mocks base method.
func (m *MockQuerier) GetPettyCash(ctx context.Context, transactionID int32) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPettyCash", ctx, transactionID)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPettyCash indicates an expected call of GetPettyCash.
func (mr *MockQuerierMockRecorder) GetPettyCash(ctx, transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPettyCash", reflect.TypeOf((*MockQuerier)(nil).GetPettyCash), ctx, transactionID)
}

// GetPurchaseOrder mocks base method.
func (m *MockQuerier) GetPurchaseOrder(ctx context.Context, id int32) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrder", ctx, id)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrder indicates an expected call of GetPurchaseOrder.
func (mr *MockQuerierMockRecorder) GetPurchaseOrder(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrder", reflect.TypeOf((*MockQuerier)(nil).GetPurchaseOrder), ctx, id)
}

// GetPurchaseOrderItemsByPurchaseOrderID mocks base method.
func (m *MockQuerier) GetPurchaseOrderItemsByPurchaseOrderID(ctx context.Context, purchaseOrderID int32) ([]db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseOrderItemsByPurchaseOrderID", ctx, purchaseOrderID)
	ret0, _ := ret[0].([]db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseOrderItemsByPurchaseOrderID indicates an expected call of GetPurchaseOrderItemsByPurchaseOrderID.
func (mr *MockQuerierMockRecorder) GetPurchaseOrderItemsByPurchaseOrderID(ctx, purchaseOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseOrderItemsByPurchaseOrderID", reflect.TypeOf((*MockQuerier)(nil).GetPurchaseOrderItemsByPurchaseOrderID), ctx, purchaseOrderID)
}

// GetQuotationByID mocks base method.
func (m *MockQuerier) GetQuotationByID(ctx context.Context, id int32) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotationByID", ctx, id)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotationByID indicates an expected call of GetQuotationByID.
func (mr *MockQuerierMockRecorder) GetQuotationByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotationByID", reflect.TypeOf((*MockQuerier)(nil).GetQuotationByID), ctx, id)
}

// GetQuotationItemsByQuotationID mocks base method.
func (m *MockQuerier) GetQuotationItemsByQuotationID(ctx context.Context, quotationID int32) ([]db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotationItemsByQuotationID", ctx, quotationID)
	ret0, _ := ret[0].([]db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotationItemsByQuotationID indicates an expected call of GetQuotationItemsByQuotationID.
func (mr *MockQuerierMockRecorder) GetQuotationItemsByQuotationID(ctx, quotationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotationItemsByQuotationID", reflect.TypeOf((*MockQuerier)(nil).GetQuotationItemsByQuotationID), ctx, quotationID)
}

// GetRole mocks base method.
func (m *MockQuerier) GetRole(ctx context.Context, id int64) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockQuerierMockRecorder) GetRole(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockQuerier)(nil).GetRole), ctx, id)
}

// GetSessionByID mocks base method.
func (m *MockQuerier) GetSessionByID(ctx context.Context, id uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockQuerierMockRecorder) GetSessionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockQuerier)(nil).GetSessionByID), ctx, id)
}

// GetSignatoryById mocks base method.
func (m *MockQuerier) GetSignatoryById(ctx context.Context, id int64) (db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignatoryById", ctx, id)
	ret0, _ := ret[0].(db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignatoryById indicates an expected call of GetSignatoryById.
func (mr *MockQuerierMockRecorder) GetSignatoryById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignatoryById", reflect.TypeOf((*MockQuerier)(nil).GetSignatoryById), ctx, id)
}

// GetUserById mocks base method.
func (m *MockQuerier) GetUserById(ctx context.Context, id int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockQuerierMockRecorder) GetUserById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockQuerier)(nil).GetUserById), ctx, id)
}

// GetUserByUserNameOrEmail mocks base method.
func (m *MockQuerier) GetUserByUserNameOrEmail(ctx context.Context, arg db.GetUserByUserNameOrEmailParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserNameOrEmail", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserNameOrEmail indicates an expected call of GetUserByUserNameOrEmail.
func (mr *MockQuerierMockRecorder) GetUserByUserNameOrEmail(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserNameOrEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByUserNameOrEmail), ctx, arg)
}

// GetUserRole mocks base method.
func (m *MockQuerier) GetUserRole(ctx context.Context, arg db.GetUserRoleParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, arg)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockQuerierMockRecorder) GetUserRole(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockQuerier)(nil).GetUserRole), ctx, arg)
}

// GetUserRoles mocks base method.
func (m *MockQuerier) GetUserRoles(ctx context.Context, userID int64) ([]db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID)
	ret0, _ := ret[0].([]db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockQuerierMockRecorder) GetUserRoles(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockQuerier)(nil).GetUserRoles), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockQuerier) GetUsers(ctx context.Context, arg db.GetUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockQuerierMockRecorder) GetUsers(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockQuerier)(nil).GetUsers), ctx, arg)
}

// ListBankDetailsByBankName mocks base method.
func (m *MockQuerier) ListBankDetailsByBankName(ctx context.Context, bankName string) ([]db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankDetailsByBankName", ctx, bankName)
	ret0, _ := ret[0].([]db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankDetailsByBankName indicates an expected call of ListBankDetailsByBankName.
func (mr *MockQuerierMockRecorder) ListBankDetailsByBankName(ctx, bankName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankDetailsByBankName", reflect.TypeOf((*MockQuerier)(nil).ListBankDetailsByBankName), ctx, bankName)
}

// ListBanks mocks base method.
func (m *MockQuerier) ListBanks(ctx context.Context) ([]db.BankDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBanks", ctx)
	ret0, _ := ret[0].([]db.BankDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBanks indicates an expected call of ListBanks.
func (mr *MockQuerierMockRecorder) ListBanks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBanks", reflect.TypeOf((*MockQuerier)(nil).ListBanks), ctx)
}

// ListCompanies mocks base method.
func (m *MockQuerier) ListCompanies(ctx context.Context, arg db.ListCompaniesParams) ([]db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanies", ctx, arg)
	ret0, _ := ret[0].([]db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompanies indicates an expected call of ListCompanies.
func (mr *MockQuerierMockRecorder) ListCompanies(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanies", reflect.TypeOf((*MockQuerier)(nil).ListCompanies), ctx, arg)
}

// ListEmployeePaymentRequests mocks base method.
func (m *MockQuerier) ListEmployeePaymentRequests(ctx context.Context, arg db.ListEmployeePaymentRequestsParams) ([]db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeePaymentRequests", ctx, arg)
	ret0, _ := ret[0].([]db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeePaymentRequests indicates an expected call of ListEmployeePaymentRequests.
func (mr *MockQuerierMockRecorder) ListEmployeePaymentRequests(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeePaymentRequests", reflect.TypeOf((*MockQuerier)(nil).ListEmployeePaymentRequests), ctx, arg)
}

// ListEmployeePettyCash mocks base method.
func (m *MockQuerier) ListEmployeePettyCash(ctx context.Context, arg db.ListEmployeePettyCashParams) ([]db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeePettyCash", ctx, arg)
	ret0, _ := ret[0].([]db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeePettyCash indicates an expected call of ListEmployeePettyCash.
func (mr *MockQuerierMockRecorder) ListEmployeePettyCash(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeePettyCash", reflect.TypeOf((*MockQuerier)(nil).ListEmployeePettyCash), ctx, arg)
}

// ListInvoiceItemsByInvoiceID mocks base method.
func (m *MockQuerier) ListInvoiceItemsByInvoiceID(ctx context.Context, invoiceID int32) ([]db.InvoiceItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvoiceItemsByInvoiceID", ctx, invoiceID)
	ret0, _ := ret[0].([]db.InvoiceItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoiceItemsByInvoiceID indicates an expected call of ListInvoiceItemsByInvoiceID.
func (mr *MockQuerierMockRecorder) ListInvoiceItemsByInvoiceID(ctx, invoiceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoiceItemsByInvoiceID", reflect.TypeOf((*MockQuerier)(nil).ListInvoiceItemsByInvoiceID), ctx, invoiceID)
}

// ListInvoices mocks base method.
func (m *MockQuerier) ListInvoices(ctx context.Context, arg db.ListInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvoices", ctx, arg)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvoices indicates an expected call of ListInvoices.
func (mr *MockQuerierMockRecorder) ListInvoices(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvoices", reflect.TypeOf((*MockQuerier)(nil).ListInvoices), ctx, arg)
}

// ListPaymentRequests mocks base method.
func (m *MockQuerier) ListPaymentRequests(ctx context.Context, arg db.ListPaymentRequestsParams) ([]db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPaymentRequests", ctx, arg)
	ret0, _ := ret[0].([]db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPaymentRequests indicates an expected call of ListPaymentRequests.
func (mr *MockQuerierMockRecorder) ListPaymentRequests(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPaymentRequests", reflect.TypeOf((*MockQuerier)(nil).ListPaymentRequests), ctx, arg)
}

// ListPettyCash mocks base method.
func (m *MockQuerier) ListPettyCash(ctx context.Context, arg db.ListPettyCashParams) ([]db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPettyCash", ctx, arg)
	ret0, _ := ret[0].([]db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPettyCash indicates an expected call of ListPettyCash.
func (mr *MockQuerierMockRecorder) ListPettyCash(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPettyCash", reflect.TypeOf((*MockQuerier)(nil).ListPettyCash), ctx, arg)
}

// ListPurchaseOrderItemsByPurchaseOrderID mocks base method.
func (m *MockQuerier) ListPurchaseOrderItemsByPurchaseOrderID(ctx context.Context, purchaseOrderID int32) ([]db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchaseOrderItemsByPurchaseOrderID", ctx, purchaseOrderID)
	ret0, _ := ret[0].([]db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchaseOrderItemsByPurchaseOrderID indicates an expected call of ListPurchaseOrderItemsByPurchaseOrderID.
func (mr *MockQuerierMockRecorder) ListPurchaseOrderItemsByPurchaseOrderID(ctx, purchaseOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchaseOrderItemsByPurchaseOrderID", reflect.TypeOf((*MockQuerier)(nil).ListPurchaseOrderItemsByPurchaseOrderID), ctx, purchaseOrderID)
}

// ListPurchaseOrders mocks base method.
func (m *MockQuerier) ListPurchaseOrders(ctx context.Context, arg db.ListPurchaseOrdersParams) ([]db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchaseOrders", ctx, arg)
	ret0, _ := ret[0].([]db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchaseOrders indicates an expected call of ListPurchaseOrders.
func (mr *MockQuerierMockRecorder) ListPurchaseOrders(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchaseOrders", reflect.TypeOf((*MockQuerier)(nil).ListPurchaseOrders), ctx, arg)
}

// ListQuotationItemsByQuotationID mocks base method.
func (m *MockQuerier) ListQuotationItemsByQuotationID(ctx context.Context, quotationID int32) ([]db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuotationItemsByQuotationID", ctx, quotationID)
	ret0, _ := ret[0].([]db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuotationItemsByQuotationID indicates an expected call of ListQuotationItemsByQuotationID.
func (mr *MockQuerierMockRecorder) ListQuotationItemsByQuotationID(ctx, quotationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuotationItemsByQuotationID", reflect.TypeOf((*MockQuerier)(nil).ListQuotationItemsByQuotationID), ctx, quotationID)
}

// ListQuotations mocks base method.
func (m *MockQuerier) ListQuotations(ctx context.Context, arg db.ListQuotationsParams) ([]db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuotations", ctx, arg)
	ret0, _ := ret[0].([]db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuotations indicates an expected call of ListQuotations.
func (mr *MockQuerierMockRecorder) ListQuotations(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuotations", reflect.TypeOf((*MockQuerier)(nil).ListQuotations), ctx, arg)
}

// ListRoles mocks base method.
func (m *MockQuerier) ListRoles(ctx context.Context, arg db.ListRolesParams) ([]db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, arg)
	ret0, _ := ret[0].([]db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockQuerierMockRecorder) ListRoles(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockQuerier)(nil).ListRoles), ctx, arg)
}

// ListSignatories mocks base method.
func (m *MockQuerier) ListSignatories(ctx context.Context, arg db.ListSignatoriesParams) ([]db.Signatory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSignatories", ctx, arg)
	ret0, _ := ret[0].([]db.Signatory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSignatories indicates an expected call of ListSignatories.
func (mr *MockQuerierMockRecorder) ListSignatories(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSignatories", reflect.TypeOf((*MockQuerier)(nil).ListSignatories), ctx, arg)
}

// ListSiteInvoices mocks base method.
func (m *MockQuerier) ListSiteInvoices(ctx context.Context, arg db.ListSiteInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSiteInvoices", ctx, arg)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSiteInvoices indicates an expected call of ListSiteInvoices.
func (mr *MockQuerierMockRecorder) ListSiteInvoices(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSiteInvoices", reflect.TypeOf((*MockQuerier)(nil).ListSiteInvoices), ctx, arg)
}

// ListUserCompanyInvoices mocks base method.
func (m *MockQuerier) ListUserCompanyInvoices(ctx context.Context, arg db.ListUserCompanyInvoicesParams) ([]db.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserCompanyInvoices", ctx, arg)
	ret0, _ := ret[0].([]db.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserCompanyInvoices indicates an expected call of ListUserCompanyInvoices.
func (mr *MockQuerierMockRecorder) ListUserCompanyInvoices(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserCompanyInvoices", reflect.TypeOf((*MockQuerier)(nil).ListUserCompanyInvoices), ctx, arg)
}

// UpdatePaymentRequest mocks base method.
func (m *MockQuerier) UpdatePaymentRequest(ctx context.Context, arg db.UpdatePaymentRequestParams) (db.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentRequest", ctx, arg)
	ret0, _ := ret[0].(db.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentRequest indicates an expected call of UpdatePaymentRequest.
func (mr *MockQuerierMockRecorder) UpdatePaymentRequest(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentRequest", reflect.TypeOf((*MockQuerier)(nil).UpdatePaymentRequest), ctx, arg)
}

// UpdatePettyCash mocks base method.
func (m *MockQuerier) UpdatePettyCash(ctx context.Context, arg db.UpdatePettyCashParams) (db.PettyCash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePettyCash", ctx, arg)
	ret0, _ := ret[0].(db.PettyCash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePettyCash indicates an expected call of UpdatePettyCash.
func (mr *MockQuerierMockRecorder) UpdatePettyCash(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePettyCash", reflect.TypeOf((*MockQuerier)(nil).UpdatePettyCash), ctx, arg)
}

// UpdatePurchaseOrder mocks base method.
func (m *MockQuerier) UpdatePurchaseOrder(ctx context.Context, arg db.UpdatePurchaseOrderParams) (db.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurchaseOrder", ctx, arg)
	ret0, _ := ret[0].(db.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePurchaseOrder indicates an expected call of UpdatePurchaseOrder.
func (mr *MockQuerierMockRecorder) UpdatePurchaseOrder(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePurchaseOrder", reflect.TypeOf((*MockQuerier)(nil).UpdatePurchaseOrder), ctx, arg)
}

// UpdatePurchaseOrderItem mocks base method.
func (m *MockQuerier) UpdatePurchaseOrderItem(ctx context.Context, arg db.UpdatePurchaseOrderItemParams) (db.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurchaseOrderItem", ctx, arg)
	ret0, _ := ret[0].(db.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePurchaseOrderItem indicates an expected call of UpdatePurchaseOrderItem.
func (mr *MockQuerierMockRecorder) UpdatePurchaseOrderItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePurchaseOrderItem", reflect.TypeOf((*MockQuerier)(nil).UpdatePurchaseOrderItem), ctx, arg)
}

// UpdateQuotation mocks base method.
func (m *MockQuerier) UpdateQuotation(ctx context.Context, arg db.UpdateQuotationParams) (db.Quotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotation", ctx, arg)
	ret0, _ := ret[0].(db.Quotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuotation indicates an expected call of UpdateQuotation.
func (mr *MockQuerierMockRecorder) UpdateQuotation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotation", reflect.TypeOf((*MockQuerier)(nil).UpdateQuotation), ctx, arg)
}

// UpdateQuotationItem mocks base method.
func (m *MockQuerier) UpdateQuotationItem(ctx context.Context, arg db.UpdateQuotationItemParams) (db.QuotationItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuotationItem", ctx, arg)
	ret0, _ := ret[0].(db.QuotationItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuotationItem indicates an expected call of UpdateQuotationItem.
func (mr *MockQuerierMockRecorder) UpdateQuotationItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuotationItem", reflect.TypeOf((*MockQuerier)(nil).UpdateQuotationItem), ctx, arg)
}

// UpdateRole mocks base method.
func (m *MockQuerier) UpdateRole(ctx context.Context, arg db.UpdateRoleParams) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, arg)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockQuerierMockRecorder) UpdateRole(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockQuerier)(nil).UpdateRole), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockQuerier) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockQuerierMockRecorder) UpdateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockQuerier)(nil).UpdateUser), ctx, arg)
}

// UpdateUserRoles mocks base method.
func (m *MockQuerier) UpdateUserRoles(ctx context.Context, arg db.UpdateUserRolesParams) (db.UserRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoles", ctx, arg)
	ret0, _ := ret[0].(db.UserRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRoles indicates an expected call of UpdateUserRoles.
func (mr *MockQuerierMockRecorder) UpdateUserRoles(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoles", reflect.TypeOf((*MockQuerier)(nil).UpdateUserRoles), ctx, arg)
}
