apiVersion: v1
kind: Service
metadata:
  name: qwetu-petroleum-api-service
spec:
  selector:
    app: qwetu-petroleum-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090

  type: LoadBalancer